### ISSUE TITLE
Can't create wallet using BitGo Express

### ISSUE THREAD

**Issue by gholami-mohammad** [BitGo/BitGoJS#1220]
I'm trying to generate a wallet using Bitgo express.

I'm running Bitgo express using docker. here is my docker-compose file:
```
version: "3.7"
services: 
    bitgoexpress:
        image: bitgosdk/express:latest
        container_name: bitgoexpress
        ports: 
            - 3080:3080
      
```

I'm calling the `wallet/generate`'s API using curl:
```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer MyToken" -d '{ "passphrase": "superlongpassword", "label": "My BitGo Wallet" }'  http://localhost:3080/api/v2/tbtc/wallet/generate
```
But got the following error:
```
"{"error":"No access token","name":"Unauthorized","requestId":"0fc06d9b8d3b19341094-0000","context":{},"message":"No access token","bitgoJsVersion":"11.15.0","bitgoExpressVersion":"9.9.6"}
```

I've created a token on  [bitgo test website](bitgo-test.com) and put that token in the request above.
